### ISSUE TITLE
RTSP session timeout value not used

### ISSUE THREAD

**Issue by skeary** [AxisCommunications/media-stream-library-js#100]
I noticed an issue when I was testing a Dahua camera with the library where a minute or so after starting to RTSP stream from it the connection would be closed by the camera. Digging further into this it appears that the camera sends a session timeout value in the setup response (e.g. `Session: 1387212806996;timeout=60`) and will close the connection unless the session is renewed within the timeout value.

I found a VAPIX document that suggests to me the appropriate way to renew the session is to send an OPTIONS request. From https://www.axis.com/files/manuals/vapix_video_streaming_52937_en_1307.pdf:

> The response returns a session identifier that should be used together with the stream control commands (for example PLAY, PAUSE and TEARDOWN). If the session header includes the timeout parameter, the session will close after the timeout time unless explicitly kept alive. Session can be kept alive by sending RTSP requests to the Axis product containing the session identifier (for example OPTIONS, see 3.2.5 RTSP OPTIONS) within the timeout time or by using RTCP messages.

As I don't have an AXIS camera handy, I can't confirm that the renewing of sessions is required for them but, based on the document above, sending an OPTIONS request periodically should work in all cases and I don't think cause an issue.

I believe I have a fix for this and will raise a PR.

Cheers,
Simon

**Comment by steabert** [comment]
Your fix was added in #124, through someone else's PR, since we assumed you had forgotten about #101.
