### ISSUE TITLE
Need TLS component similar to TCP one

### ISSUE THREAD

**Issue by JadChahine** [AxisCommunications/media-stream-library-js#112]
Hello,

I am looking for a TLS component similar to the TCP one mentioned in https://github.com/AxisCommunications/media-stream-library-js/tree/master/lib/components/tcp

What modifications should I do? other than using a TLS port

**Comment by JadChahine** [comment]
Any update?

**Comment by steabert** [comment]
We use a `net.Socket`, and I guess you'll need to use a `tls.TLSSocket`, see https://nodejs.org/dist/latest-v11.x/docs/api/tls.html#tls_class_tls_tlssocket, which is returned by `tls.connect`, see https://nodejs.org/dist/latest-v11.x/docs/api/tls.html#tls_tls_connect_options_callback.
So you'll need to replace the `const { connect } = require('net')` at the top of the file to `const { connect } = require('tls')`, and then adapt it to handle this kind of socket.
