### ISSUE TITLE
Include TypeScript Definitions to Published NPM

### ISSUE THREAD

**Issue by Kirkify** [AxisCommunications/media-stream-library-js#133]
First off I want to thank you guys for open sourcing this library and also recently updating to TypeScript.  This new issue references a recently closed [enhancement request](https://github.com/AxisCommunications/media-stream-library-js/issues/68), I was hoping you guys could include the typescript definitions when publishing the repo to NPM?

**Comment by steabert** [comment]
Absolutely correct, thanks for spotting this and your contribution!
