### ISSUE TITLE
MJPEG on Safari OS X not working

### ISSUE THREAD

**Issue by reijosirila** [AxisCommunications/media-stream-library-js#145]
https://github.com/AxisCommunications/media-stream-library-js/blob/1dcdad4de637a31291a4f7c6ab6de656a29a5475/lib/components/canvas/index.ts#L119

```
window.createImageBitmap is not a function. (In 'window.createImageBitmap(blob)', 'window.createImageBitmap' is undefined)
```

Maybe drawImage for Safari and transferFromImageBitmap for Chrome/Firefox? 

Both versions, 5 and 6

**Comment by steabert** [comment]
Indeed, we wrongly assume that `window.createImageBitmap` is available because there is a `bitmaprenderer` context. Instead, we should check for it and use the fallback if it's not available.

**Comment by reijosirila** [comment]
For some reason fallback didn't work on a Safari also.

**Comment by steabert** [comment]
Do you get a more specific error?

**Comment by reijosirila** [comment]
I'll try to debug it as soon as possible and give a feedback.
