### ISSUE TITLE
Expose MessageType enum

### ISSUE THREAD

**Issue by Kirkify** [AxisCommunications/media-stream-library-js#147]
First off thanks again for creating this library, I'm a big fan of your pipeline architecture, it gives me the ability to create my own component and re-use some of yours in a custom pipeline.  One problem I am having is after I transform my stream in my custom component, I wish to send that data to the Mp4Muxer component, doing so I need to add a type of MessageType.SDP or MessageType.ELEMENTARY, currently I have had to hardcode a copy of the MessageType enum in my project.  It would make it much easier if this enum was exposed in your library.  I will try and create a pull request with this change later today

**Comment by steabert** [comment]
Nice to hear that the architecture works out for you. Feel free to expose more types if necessary.
