### ISSUE TITLE
Some Axis camera not supporting token api(/axis-cgi/rtspwssession.cgi)

### ISSUE THREAD

**Issue by kulwantsharma** [AxisCommunications/media-stream-library-js#265]
Hi,

I have the below cameras with the firmware version. I am using the API ( /axis-cgi/rtspwssession.cgi ) to fetch token from the camera but these camera doesn't support this API. 

M5054  6.53.2.1(latest firmware version)
M5065  6.53.2.2(latest firmware version)

With my other cameras that are having firmware above 8+ returning me the token with same api and I am using token to stream like below. I have used java code to get the token from the camera using digest auth and passing the token to javascript piece of code for streaming. Previously I was using the authorize method from simple-player.js which was causing a pop up for username and password. Since I didn't want popup so implemented in java.
 
```
const pipeline = new Pipeline({
          ws: { uri: `${ wsScheme }://${ host }/rtsp-over-websocket?rtspwssession=` + token },
          rtsp: { uri: `rtsp://${ host }/axis-media/media.amp?videocodec=${ encoding }` },
        mediaElement
      });
```

Is there any other way to get the token from those cameras (mentioned on top)? or is there any other way I can achieve streaming? 

Can streaming be achieved from those cameras that don't support token API using media-streaming-library?

Thanks,
Kulwant Sharma

**Comment by steabert** [comment]
If there is no token API, then as far as I can tell, those do no support WebSocket yet, so you will not be able to stream directly from the camera to a browser. The only way would be to put a WebSocket proxy in-between to forward the RTP stream over WebSocket.
