### ISSUE TITLE
Internet Explorer 11 support ?

### ISSUE THREAD

**Issue by yellowiscool** [AxisCommunications/media-stream-library-js#37]
Hei,

We receives errors from this library, with our users using Internet Explorer 11. Do you have any plan to support internet explorer 11, or should we simply ask our users to use another web browser ?

**Comment by steabert** [comment]
Currently IE11 is not supported, but this is just a matter of building the bundle with the right polyfill.
I've marked this as a change request, and will add it soon(ish).
