### ISSUE TITLE
components.Component is undefined in browser example h264-overlay-player.js

### ISSUE THREAD

**Issue by yangpu** [AxisCommunications/media-stream-library-js#389]
run browser example (h264-overlay-player.js), throw exception:

`
h264-overlay-player.js:72 Uncaught TypeError: Cannot read property 'peek' of undefined
`

no Component exported from components:

`
const runScheduler = components.Component.peek(msg => scheduler.run(msg))
 `

**Comment by steabert** [comment]
Fixed in #298
