### ISSUE TITLE
Chrome pauses stream when tab is changed

### ISSUE THREAD

**Issue by MarcelPawlo** [AxisCommunications/media-stream-library-js#418]
Using "examples/browser/camera/simple.html" and playing a RTSP stream, it will stop when I change the tab in Chrome 83. When switching back, you can see that the timestamp hasn't continued.

Feature is called "Background Tab Throttling" and might be a browser problem occurred in chrome 57. Just wondering why other players do not stop while switching tabs with Chrome 83.

Any suggestions?

**Comment by steabert** [comment]
Yes, you need to handle pause/resume in the player, this library just provides the lower level functionality. You can look at https://github.com/AxisCommunications/media-stream-player-js/blob/master/lib/Player.tsxfor an example how to do this (by checking the `visibilityState`).

**Comment by MarcelPawlo** [comment]
Thanks for the tip with the advice with the visibilityState.
Don't get me wrong, but I was looking for a way to NOT pause the player when changing the tab with Chrome. My solution is to establish a new RTSP pipeline like this: `document.addEventListener("visibilitychange", () => if (!(document.visibilityState === "hidden" && document.hidden)) createRtspPipeline(videoNode), false);`

**Comment by piyush-vvdn** [comment]
I am also facing the same problem, can you tell me, how to use this?
