### ISSUE TITLE
No MediaSource support with Samsung Internet 

### ISSUE THREAD

**Issue by fungiboletus** [AxisCommunications/media-stream-library-js#42]
Hei,

We have one user with Samsung Internet  7.2. This browser doesn't support MediaSource by default, so the media-stream-library-js triggers the exception `window.MediaSource is not a constructor`. A more explicit error message such as "this web browser doesn't support media sources" could be a minor improvement.

**Comment by steabert** [comment]
Just wanted to mention that there is a function to detect supported formats, which can be used to avoid problems like this.

But sure, a better error message couldn't hurt.

**Comment by reijosirila** [comment]
> Just wanted to mention that there is a function to detect supported formats, which can be used to avoid problems like this.
> 

Oh. Where can I find this function ?

**Comment by steabert** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/isTypeSupported
