### ISSUE TITLE
MJPEG/RTSP crashes Firefox 79 tab.

### ISSUE THREAD

**Issue by reijosirila** [AxisCommunications/media-stream-library-js#443]
To Reproduce just open example `/test/mjpeg.html` on a Firefox 79. On a Firefox 78 it works great. Try to do some refreshes. 

**Environment:**
 - OS: Tested on Windows, Linux and MacOS
 - Browser Firefox
 - Version 79

**Comment by steabert** [comment]
I reproduce both a freeze, as well as a console error on Firefox 81. The console error happens also on Chromium:

```
closing socket due to incoming error Error: no quantization header present
```

**Comment by steabert** [comment]
I cannot reproduce this with latest main branch on Firefox 87.
