### ISSUE TITLE
support H265 in the future will be exciting

### ISSUE THREAD

**Issue by wst-casd** [AxisCommunications/media-stream-library-js#512]
This tool is so fascinating. But when the camera video codec is h265, this tool can't handle that. If it can support h265, it will be more useful!

Thanks

**Comment by lekoaf** [comment]
Yeah, that would be cool. Except that the browser support for h.265 is severely lacking.

https://caniuse.com/?search=h265

**Comment by ggregory8** [comment]
Just revisiting this topic now h265 is supported on a few browsers i.e Edge. Does the media-stream-library handle H265 RTSP streams yet? I can't see any reference to this in the docs yet.

**Comment by lekoaf** [comment]
> Just revisiting this topic now h265 is supported on a few browsers i.e Edge. Does the media-stream-library handle H265 RTSP streams yet? I can't see any reference to this in the docs yet.

Nope, we haven't looked at H.265 support yet.
