### ISSUE TITLE
How to integrate media-stream-library inside Angular8 app

### ISSUE THREAD

**Issue by JackZhai2018** [AxisCommunications/media-stream-library-js#534]
When I try to use Html5VideoPipeline in my Angular 8 application , I get the error as following.
Anybody had ever integrate media-stream-library inside angular application successfully?
Can you give a sample for me.

----------------
import {components, pipelines} from 'media-stream-library';
const pipeline = new pipelines.Html5VideoPipeline({

----------------
ERROR TypeError: Cannot read property 'Html5VideoPipeline' of undefined

**Comment by lekoaf** [comment]
I think you need to go deeper. `import {pipelines} from 'media-stream-library/dist/esm/index.browser'`.

**Comment by steabert** [comment]
It depends how Angular bundles stuff, unfortunately I don't know anything about Angular. If you import like @lekoaf wrote, you'll need to bundle the browserify parts yourself.
