### ISSUE TITLE
Stream rtsp over websocket and save into file with Node CLI

### ISSUE THREAD

**Issue by JackZhai2018** [AxisCommunications/media-stream-library-js#546]
I try to stream rtsp over websocket and save into file with Node CLI.
so I create a new pipeline, can it work for me?

----------------------------------------------------

class CliWsMp4Pipeline extends rtsp_mp4_pipeline_1.RtspMp4Pipeline {

    constructor(config) {
        const { ws: wsConfig, rtsp: rtspConfig, auth: authConfig, file: fileConfig} = config;
        super(rtspConfig);
        if (authConfig) {
            const auth = new auth_1.Auth(authConfig);
            this.insertBefore(this.rtsp, auth);
        }

	var accessfile = fs.createWriteStream(file.path);
        const dataSaver = process.stdout.isTTY
            ? (msg) => console.log(msg.type, msg.data)
            : (msg) => process.stdout.pipe(accessfile).write(msg.data);
        const videoSink = component_1.Sink.fromHandler(dataSaver);

        const waitForWs = ws_source_1.WSSource.open(wsConfig);
        this.ready = waitForWs.then((wsSource) => {
            wsSource.onServerClose = () => {
                this.onServerClose && this.onServerClose();
            };
            this.prepend(wsSource);
	    this.append(videoSink);
            this._src = wsSource;
        });
    }

}

----------------------------------------------------------------------------------------------------

**Comment by JackZhai2018** [comment]
Anyone know how to write the init segment into mp4 file with commponents provided in this library?

**Comment by steabert** [comment]
If you want to write MP4 to a file, you'll need to add the RTSP session and parser, H.264 and AAC depay, and MP4 muxer components. The same are used for the html5 video pipeline.
