### ISSUE TITLE
how to get frame-by-frame image from RTP over websocket 

### ISSUE THREAD

**Issue by JackZhai2018** [AxisCommunications/media-stream-library-js#575]
How to get frame-by-frame image from RTP over websocket?
How to design the pipeline to match this need?

**Comment by steabert** [comment]
You cannot get images from the RTP pipeline, just data. It's the browser that renders the eventual image.

If you use JPEG over RTP, you get the frames as separate images, and they are rendered in a canvas.
When using e.g. H.264, you could take snapshots from the `<video>` element.

Without more details describing your use-case it's difficult to understand your question about the pipeline.

**Comment by steabert** [comment]
Closing for now since inactive, but please continue discussion if you have more info, thanks.
