### ISSUE TITLE
Different video latencies if multiple streams from the same camera are played

### ISSUE THREAD

**Issue by fau-xx** [AxisCommunications/media-stream-library-js#591]
We use the axis media stream library extensively to display streams from Axis cameras like the V5915 or P5635-E and we noticed that the latencies differ if the same rtsp url is requested multiple times. If the same is done with the VLC Player all streams are exactly synchronous, which leads me to believe that the same rtsp stream is reused (which is prefered by us). Is there a way to achieve this behaviour using the media stream library?
I am aware that perfect synchronicity cannot be achieved with http, because of the different arrival times of the data chunks, but we experiencing differences in latency of about 10 seconds.

Also i noticed that the time range inside the "buffered"-property of the video element is growing and almost matches the observed latency. Is it possible that the camera is sending broken video chunks if the workload of the camera increases, which disturbs the media stream library and cause the buffer  (and the latency) to grow? Opening multiple rtsp streams with VLC does not seem to affect the performance of the camera.

Edit:
The camera skips video frames or parts of the stream under workload and this can lead to following situation:
videoElement.currentTime = 20
videoElement.buffered.start(0) = 21
videoElement.buffered.end(0) = 23

1 second is missing between currentTime and the buffered video. As an temporary solution, i can detect this situations and set the currentTime in between the buffered time range.

**Comment by steabert** [comment]
When you use RTSP in the browser with media-stream-library, the camera has to send that over WebSocket, which affects the performance, but I'm not sure how much. However, if the camera starts dropping frames because of that, you will definitely see problems with playback, we cannot handle that properly with the MediaSource API, as the browser takes full control over the decoding part.

Which firmware do you use on those cameras?

**Comment by fau-xx** [comment]
The AXIS V5915 PTZ Network Camera uses firmware version 8.45.3.1

**Comment by steabert** [comment]
If it doesn't occur in VLC it could be related to the WebSocket part, since there the audio and video are multiplexed over TCP. I wonder if you can configure VLC to make it request multiplexed audio/video (I think there is a `mux` option or sth).
