### ISSUE TITLE
Cypress Does Not Support Linux 32 Bit

### ISSUE THREAD

**Issue by toqana** [AxisCommunications/media-stream-library-js#593]
Linux 32bit is not supported #6110, see https://github.com/cypress-io/cypress/issues/6110

Raspberry Pi OS 10 on RPi3 B+

```uname -a
Linux <hostname> 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux
```

```cd ~
git clone https://github.com/AxisCommunications/media-stream-library-js.git
cd ~/media-stream-library-js
npm install
```

```> cypress@6.4.0 postinstall /home/pi/media-stream-library-js/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 6.4.0)

  ✖  Downloading Cypress    
    → Cypress Version: 6.4.0
     Unzipping Cypress      
     Finishing Installation 
The Cypress App could not be downloaded.
```

URL: https://download.cypress.io/desktop/6.4.0?platform=linux&arch=ia32
```Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found
```

After downloading the Linux zip file from https://docs.cypress.io/guides/getting-started/installing-cypress.html#System-requirements

```./Cypress
bash: ./Cypress: cannot execute binary file: Exec format error
```

If possible, please provide support for Linux 32-bit.

**Comment by steabert** [comment]
You only need a 64-bit system if you want to run Cypress tests. Other than that the rest should work?

You can use `CYPRESS_INSTALL_BINARY=0 npm install` to skip Cypress binary during installation.
