### ISSUE TITLE
H264 is workig fine, can we play H265?

### ISSUE THREAD

**Issue by Nidheeshv0312** [AxisCommunications/media-stream-library-js#619]
Tell us what's on your mind.

**Comment by Nidheeshv0312** [comment]
We used websokify to send RTSP h264 stream to ws and used that with this application and we were able to get the stream o browser
 similary can we do with h265?

**Comment by pppaulpeter** [comment]
the answer is no? it doesn't support h265, right?

**Comment by lekoaf** [comment]
Nope, sorry.

https://caniuse.com/?search=H.265
