### ISSUE TITLE
Not worrking in  IE11 

### ISSUE THREAD

**Issue by Nidheeshv0312** [AxisCommunications/media-stream-library-js#629]
when trying to test in IE11 getting this 
HTML1300: Navigation occurred.
h264.html
SCRIPT1002: Syntax error
media-stream-library.min.js (2,244)
SCRIPT1010: Expected identifier
h264-player.js (1,7)

**Comment by steabert** [comment]
We don't support IE11, we only provide some documentation on how one could (possibly) make it work.
