### ISSUE TITLE
add md5 to basic sample

### ISSUE THREAD

**Issue by howudodat** [AxisCommunications/media-stream-library-js#653]
the basic sample re-auths, but forces a pop-up.  Can a sample be provided that allows for the credentials to come from variables?  
adding to fetch options:
`'Authorization': 'Basic ' + btoa('username:password'),`
doesn't help because the cameras dont support basic auth

**Comment by howudodat** [comment]
oops, digest authentication is intercepted by the browsers...never midn

**Comment by revanreddy** [comment]
Did you find any solution for this ?
