### ISSUE TITLE
Auth over websocket 

### ISSUE THREAD

**Issue by cubecleveland** [AxisCommunications/media-stream-library-js#661]
Hi,

I saw some question like this before but with no exact solution

 is there an example to do a websocket auth and show the feed in a browser window over rtsp, which will eliminate the need for the difest popup.

If that is not possible, is there anyway to set a user on a camera with basic auth that will eliminate the need for popup.

Basically we are in the same LAN trying to just view the camera whithin an app but without bothering the user for a popup.
Using Axis cameras. We have the user/pass stord in a db so we can pass it..
any help appreciated...

**Comment by MennoSaey** [comment]
how did you solve this?
