### ISSUE TITLE
Broken player when bundling with rollup (Vite).

### ISSUE THREAD

**Issue by jankaifer** [AxisCommunications/media-stream-library-js#665]
**Describe the bug**
Everything works in CRA or [Vite](https://github.com/vitejs/vite) dev-mode (esbuild).
But it breaks when bundled with Vite prod-mode (rollup).

**To Reproduce**
1. Bootstrap Vite project
2. Add `<Player hostname="..."/>`
3. run `yarn build`

I created a simple project here: https://stackblitz.com/edit/vitejs-vite-afydj5?file=src/App.tsx
Just change `HOSTNAME` IP of your camera.
But you need to force your browser to connect to camera via http from a https site.
Or you can download it and run it locally from `localhost`.

**Screenshot**
<img width="1426" alt="CleanShot 2022-04-12 at 23 52 28@2x" src="https://user-images.githubusercontent.com/12820484/163060720-012334d6-9e05-492f-8103-a9659b5b7bea.png">

**Environment (please complete the following information):**
 - OS: Linux&Mac (don't have Windows)
 - Browser (all tested browser had this issue): Mac(Chrome, Firefox), Linux(Chrome, Firefox)
 - Version 7.0.0

**Workaround**
We just manually add `<script/>` with a minified build of this library.
Then it works as expected, but it's suboptimal.

**Comment by steabert** [comment]
Looking at your example project you're not replacing `streams` with `stream-browserify` ? That's an alias that is in our example vite configs which you'll also need when building.

When you use the bundle that was built with esbuild, it has already done that since esbuild respects the browser field in `package.json` to replace the package.

**Comment by jankaifer** [comment]
Thanks a lot for the reply. I don't work that project anymore, but I'll pass this along.
