### ISSUE TITLE
Unable to resolve 'media-stream-library' module when bundling for browser

### ISSUE THREAD

**Issue by JoshThor** [AxisCommunications/media-stream-library-js#678]
**Describe the bug**
When attempting to import components from 'media-stream-library' webpack throws the following error:
`Module not found: Error: Can't resolve 'media-stream-library' in '/home/redacted/dev/issue-test/src'`

**To Reproduce**
To quickly reproduce you can create a simple React application and attempt to use media-stream-library

1. run `npx create-react-app issue-test`
2. run `cd issue-test`
3. run `npm install && npm install media-stream-library`
4. add the following to the top of `src/app.js`:
```
import {Html5VideoPipeline} from 'media-stream-library';
const test = new Html5VideoPipeline({mediaElement: new HTMLVideoElement()});
```
5. run `npm start`

**Environment (please complete the following information):**
 - OS: Windows, Linux
 - Browser: Chrome
 - Version: 11.1.1

**Additional context**
 I was able to reproduce this issue in both and Angular and React App.

**Possible Solution**
I was able to fix the issue locally by updating the `package.json` browser field to:
```
  "browser": {
    "dist/node-cjs.js": "./dist/browser-cjs.js",
    "dist/node-esm.js": "./dist/browser-esm.js",
    "stream": "stream-browserify"
  },
```

**Comment by tigrenok00** [comment]
@JoshThor 

Hi,

did  you do it like this?

` 
 "exports": {

    "types": "./dist/src/index.browser.d.ts",
    "browser": {
      "types": "./dist/src/index.browser.d.ts",
      "require": "./dist/browser.cjs",
      "import": "./dist/browser.mjs"
    },
    "node": {
      "types": "./dist/src/index.node.d.ts",
      "require": "./dist/node.cjs",
      "import": "./dist/node.mjs"
    }
  },

```
  "browser": {
    "stream": "stream-browserify",
    "dist/node-cjs.js": "./dist/browser-cjs.js",
    "dist/node-esm.js": "./dist/browser-esm.js"
  },
`
```

I'm getting error 
`Error: Module not found: Error: Package path ./dist/browser.mjs is not exported from package C:\XX\XX\XX\node_modules\media-stream-library (see exports field in C:\XX\XX\XX\node_modules\media-stream-library\package.json)`
