### ISSUE TITLE
Feature request: Typescript definition

### ISSUE THREAD

**Issue by gaetancollaud** [AxisCommunications/media-stream-library-js#68]
Nowadays a lot of js library provide definition for typescript. I would be nice to follow the movement. :wink: 

I know that it's not done in 5min, but I would be of a great help for those working with typescript.

I would gladly help you if this request is accepted.

**Comment by steabert** [comment]
This sounds like a great idea.

Since I'm no expert regarding Typescript, if you feel up to the task, I'll gladly consider any pull requests.

Keep in mind to:
- not affect non-typescript users
- document usage

**Comment by steabert** [comment]
I've now started to look into this myself, hopefully I can produce some kind of PR soon.

**Comment by steabert** [comment]
Typescript arrived with #123
