### ISSUE TITLE
Support for G.711 uLaw audio codec?

### ISSUE THREAD

**Issue by chetbox** [AxisCommunications/media-stream-library-js#681]
Hi! Thanks for this really helpful library. 📺 👀 

We're using it with IP cameras to stream an RTSP video feed to the browser but there doesn't seem to be any audio. Running `node examples/node/player.js --uri rtsp://IP:PORT/PATH | vlc -` shows that there is no audio track in VLC. If I play the RTSP stream directly in VLC there is an audio track present and I can hear it.

The Uniview cameras we use only have one option for audio compression: G.711 which I believe is using the uLaw format. `media-stream-library-js` seems to only mention AAC audio. Does it assume that all audio will be in the AAC format? How do I stream uLaw audio and play it in the browser?

**Comment by lekoaf** [comment]
This library only has support for AAC audio format. But you can always write a component for uLaw if you'd like.
