### ISSUE TITLE
Stream freezes when window is not focused, resumes when in focus

### ISSUE THREAD

**Issue by Pedro-Leitek** [AxisCommunications/media-stream-library-js#682]
Hi,

I was able to use de media Stream Library JS. I can see the stream but everytime the window/tab of the browser is not in focus because I've switched to another tab or minimized the browser, I see a delay on the stream. It is like if the stream freezed when the tabs were switched and resumed when the tab was opened again. I would like to know what can I do to see the stream live (real-time) no matter how long the tab is not focused. Thanks

**Comment by steabert** [comment]
The browser will limit processing for tabs that are not visible. The only solution is to refresh the stream when the tab is visible again. To do that you can listen to the 'visibilitychange' event on the document, there is an example in `player/src/BasicPlayer.tsx` that pauses and plays, instead you would have to force a refresh.
