### ISSUE TITLE
Update of examples required since v11.0.0

### ISSUE THREAD

**Issue by milbrandt** [AxisCommunications/media-stream-library-js#690]
**Describe the bug**

With the breaking change in v11.0.0 (see #666) , "direct imports from esm, cjs, or es5 will no longer work,"

**To Reproduce**

At least https://github.com/AxisCommunications/media-stream-library-js/blob/main/examples/node/player.js still contains
```js
const { pipelines } = require('../../dist/cjs/index.node.js')
```

**Comment by steabert** [comment]
Should be solved now, the examples have been lifted out of the respective packages and changed so that they are more representative for how one should use the libraries.
