### ISSUE TITLE
React CRA - Module parse failed (media-stream-library.min.js)

### ISSUE THREAD

**Issue by Taerarenai** [AxisCommunications/media-stream-library-js#713]
**Describe the bug**
The title pretty much sums it up. I'm trying to test the basic player (or any player for that matter) and it fails to compile.

```
./node_modules/media-stream-library/dist/media-stream-library.min.js 8142:39
Module parse failed: Unexpected token (8142:39)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         _controlURL(e) {
|           if (void 0 !== e && /^[^:]+:\/\//.test(e)) return e;
>           const t = this._contentBase ?? this._contentLocation ?? this.uri;
|           if (null == t) throw new Error("relative or missing control attribute but no base URL available");
|           return void 0 === e || "*" === e ? t : new URL(e, t).href;
```

**To Reproduce**

1. Install React using CRA (JS or TypeScript)
2. Install dependencies (luxon & styled-components)
3. Import a player (BasicPlayer) and add the component in react
4. Run the dev server (npm start) 

**Environment (please complete the following information):**
 - OS: Windows
 - Node V: 12.9.8
 - Version: media-stream-player 5.3.0

**Additional context**
As mentioned, this is an extremely clean CRA project and I've tried both JS and TS (thinking at first it had something to do with styled-components not working without config on typescript)

**Comment by steabert** [comment]
The minified bundle should no longer be referenced. We should probably re-test with CRA after #767 is merged.
