### ISSUE TITLE
Media stream player CRA React fail

### ISSUE THREAD

**Issue by cmpeguerog** [AxisCommunications/media-stream-library-js#726]
**Describe the bug**
Unable to use stream-media-player on a clean CRA with installed peer dependencies. When **yarn start** command is invoked this error is prompted: **Can't resolve 'media-stream-library' in 'xxx\node_modules\media-stream-player\dist'**

**Environment (please complete the following information):**
 - OS:Windows
 - Browser: Chrome

**Comment by steabert** [comment]
Thanks for your report. Do you have a minimal example how to reproduce this?

**Comment by steabert** [comment]
Also: note that media-stream-library is a peer dependency of media-stream-player, so you'll need to install it explicitly.

**Comment by ErikMN** [comment]
I had the same problem, I worked around it by using react-app-rewired described here: https://github.com/AxisCommunications/media-stream-library-js/issues/743

**Comment by steabert** [comment]
Duplicate of #743
