### ISSUE TITLE
Motion jpeg and Mp4 codec not supported 

### ISSUE THREAD

**Issue by revanreddy** [AxisCommunications/media-stream-library-js#755]
We have tried the streaming with codec types as mjpeg and mp4 by following examples provided in the code. but we couldn't get the stream. 

We have tried the following models of axis cameras:

AXIS 213, M1145, Q1798.

Please let us know is there any limitations  with library or axis cameras 

Thanks

**Comment by steabert** [comment]
There should be no limitations with regards to MJPEG at least, as for streaming MP4 that depends on if you use H.264 over RTSP or streaming MP4 directly (the latter needs fw 9.80).

However, I've had problems streaming both MJPEG and MP4 on Google Chrome, but I haven't investigated it much further.
Which browser did you use? Can you try with Firefox?
